import tkinter as tk

root = tk.Tk()
root.title('MARKSHEET')

name_label = tk.Label(root, text = 'Name')
name_label.pack()
name_entry = tk.Entry(root)
name_entry.pack()

roll_label = tk.Label(root, text = 'Roll.No')
roll_label.pack()
roll_entry = tk.Entry(root)
roll_entry.pack()

reg_label = tk.Label(root, text = 'Reg.No')
reg_label.pack()
reg_entry = tk.Entry(root)
reg_entry.pack()

grade_label = tk.Label(root, text='Grade', width=30)
grade_label.pack()
grade_entry = tk.Entry(root)
grade_entry.pack()
grade_label = tk.Label(root, text='', width=30)
grade_label.pack()
grade_entry = tk.Entry(root)
grade_entry.pack()
grade_label = tk.Label(root, text='', width=30)
grade_label.pack()
grade_entry = tk.Entry(root)
grade_entry.pack()
grade_label = tk.Label(root, text='', width=30)
grade_label.pack()
grade_entry = tk.Entry(root)
grade_entry.pack()

srl_label = tk.Label(root, text='Subject:')
srl_label.pack()
srl_label = tk.Label(root, text='cs201')
srl_label.pack()
srl_label = tk.Label(root, text='ma201')
srl_label.pack()
srl_label = tk.Label(root, text='ec201')
srl_label.pack()
srl_label = tk.Label(root, text='cs202')
srl_label.pack()
submit_button = tk.Button(root, text='submit')
submit_button.pack()
root.mainloop()